import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

const APP_NAME = "9router";
const CLI_TOKEN_HEADER = "x-9r-cli-token";
const CLI_TOKEN_SALT = "9r-cli-auth";
const DEFAULT_PORT = 20128;
const DEFAULT_BASE_URL = `http://127.0.0.1:${DEFAULT_PORT}/v1`;

export const NINEROUTER_BASE_URL = process.env.NINEROUTER_BASE_URL || DEFAULT_BASE_URL;
export const NINEROUTER_DASHBOARD_URL =
  process.env.NINEROUTER_DASHBOARD_URL || `http://127.0.0.1:${DEFAULT_PORT}/dashboard`;

function getDataDir() {
  if (process.env.DATA_DIR) return process.env.DATA_DIR;
  if (process.platform === "win32") {
    return path.join(process.env.APPDATA || path.join(os.homedir(), "AppData", "Roaming"), APP_NAME);
  }
  return path.join(os.homedir(), `.${APP_NAME}`);
}

function getCliToken() {
  const dataDir = getDataDir();
  const machineId = fs.readFileSync(path.join(dataDir, "machine-id"), "utf8").trim();
  const secret = fs.readFileSync(path.join(dataDir, "auth", "cli-secret"), "utf8").trim();
  return crypto
    .createHash("sha256")
    .update(machineId + CLI_TOKEN_SALT + secret)
    .digest("hex")
    .substring(0, 16);
}

export async function apiRequest(method, apiPath, body = null) {
  const base = NINEROUTER_DASHBOARD_URL.replace(/\/dashboard$/, "");
  const headers = {
    "Content-Type": "application/json",
    [CLI_TOKEN_HEADER]: getCliToken(),
  };
  const init = { method, headers };
  if (body) init.body = JSON.stringify(body);

  const res = await fetch(`${base}${apiPath}`, init);
  const text = await res.text();
  let data = {};
  try {
    data = text ? JSON.parse(text) : {};
  } catch {
    data = { raw: text };
  }
  return { success: res.ok && !data.error, statusCode: res.status, data, error: data.error };
}

export async function ensureApiKey(name = "ide-hub") {
  const existing = await apiRequest("GET", "/api/keys");
  const keys = existing.data?.keys || [];
  const found = keys.find((k) => k.name === name);
  if (found?.key) return found.key;

  const created = await apiRequest("POST", "/api/keys", { name });
  if (!created.success) {
    throw new Error(`createApiKey failed: ${created.error || created.statusCode}`);
  }
  return created.data.key;
}

export async function healthCheck() {
  const base = NINEROUTER_DASHBOARD_URL.replace(/\/dashboard$/, "");
  const res = await fetch(`${base}/api/health`);
  const data = await res.json().catch(() => ({}));
  return { ok: res.ok && data.ok === true, statusCode: res.status, data };
}

export async function chatSmoke(apiKey, model = "premium-coding") {
  const res = await fetch(`${NINEROUTER_BASE_URL}/chat/completions`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model,
      messages: [{ role: "user", content: "reply with exactly: ok" }],
      max_tokens: 8,
    }),
  });
  const text = await res.text();
  let data = {};
  try {
    data = text ? JSON.parse(text) : {};
  } catch {
    data = { raw: text };
  }
  return { ok: res.ok, statusCode: res.status, data };
}

export function getLocalEnvPath() {
  return path.join(os.homedir(), ".9router", "ide-hub.env");
}

export function writeLocalEnv({ apiKey, model }) {
  const envPath = getLocalEnvPath();
  fs.mkdirSync(path.dirname(envPath), { recursive: true });
  const body = [
    "# 9router local IDE hub — generated by scripts/9router/setup.mjs",
    "# Do not commit. Load in shell:  . $env:USERPROFILE\\.9router\\ide-hub.env",
    `NINEROUTER_BASE_URL=${NINEROUTER_BASE_URL}`,
    `NINEROUTER_API_KEY=${apiKey}`,
    `NINEROUTER_MODEL=${model}`,
    `OPENAI_BASE_URL=${NINEROUTER_BASE_URL}`,
    `OPENAI_API_KEY=${apiKey}`,
    `ANTHROPIC_BASE_URL=${NINEROUTER_BASE_URL}`,
    `ANTHROPIC_AUTH_TOKEN=${apiKey}`,
    "",
  ].join("\n");
  fs.writeFileSync(envPath, body, { mode: 0o600 });
  return envPath;
}

export function readJsonIfExists(filePath) {
  if (!fs.existsSync(filePath)) return null;
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

export function writeJson(filePath, data) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, `${JSON.stringify(data, null, 2)}\n`, "utf8");
}

export async function getConnectedProviders() {
  const providers = await apiRequest("GET", "/api/providers");
  return providers.data?.connections || [];
}

export function resolveDefaultModel(connections, comboResult = null) {
  const comboReady = comboResult?.ok && (comboResult.modelsInCombo?.length >= 2 || comboResult.connected?.length >= 2);
  if (comboReady && comboResult?.comboModelId) return comboResult.comboModelId;
  if (comboResult?.ok && comboResult?.modelId) return comboResult.modelId;
  const names = new Set(connections.map((c) => c.provider));
  if (names.has("cursor")) return "cu/default";
  if (names.has("copilot")) return "cp/default";
  if (names.has("antigravity")) return "ag/default";
  if (names.has("codex")) return "cx/gpt-5.3-codex";
  return process.env.NINEROUTER_MODEL || "premium-coding";
}

export function isSmokeRouted(smoke) {
  return (
    smoke.ok ||
    smoke.statusCode === 429 ||
    (typeof smoke.data?.error?.message === "string" &&
      /\[(cursor|copilot|codex|kiro|combo|antigravity|ag)\//i.test(smoke.data.error.message))
  );
}
